export type Role = "admin" | "manager" | "employee";

export interface User {
  id: string;
  name: string;
  email: string;
  role: Role;
  status: "active" | "inactive";
  avatar: string;
  joinedAt: string;
}

export interface Project {
  id: string;
  name: string;
  description: string;
  status: "pending" | "deploying" | "live";
  assignees: string[];
  createdAt: string;
  apiKey?: string;
}

export const credentials = [
  { email: "admin@triffid.ai", password: "admin123", role: "admin" as Role, name: "Alex Admin" },
  { email: "manager@triffid.ai", password: "manager123", role: "manager" as Role, name: "Morgan Manager" },
  { email: "employee@triffid.ai", password: "employee123", role: "employee" as Role, name: "Emma Employee" },
];

export const users: User[] = [
  { id: "1", name: "Alex Admin", email: "admin@triffid.ai", role: "admin", status: "active", avatar: "AA", joinedAt: "2024-01-15" },
  { id: "2", name: "Morgan Manager", email: "manager@triffid.ai", role: "manager", status: "active", avatar: "MM", joinedAt: "2024-02-20" },
  { id: "3", name: "Emma Employee", email: "employee@triffid.ai", role: "employee", status: "active", avatar: "EE", joinedAt: "2024-03-10" },
  { id: "4", name: "Sam Smith", email: "sam@triffid.ai", role: "employee", status: "active", avatar: "SS", joinedAt: "2024-03-15" },
  { id: "5", name: "Jane Doe", email: "jane@triffid.ai", role: "employee", status: "inactive", avatar: "JD", joinedAt: "2024-04-01" },
  { id: "6", name: "Chris Lee", email: "chris@triffid.ai", role: "manager", status: "active", avatar: "CL", joinedAt: "2024-04-10" },
  { id: "7", name: "Taylor Brown", email: "taylor@triffid.ai", role: "employee", status: "active", avatar: "TB", joinedAt: "2024-05-01" },
  { id: "8", name: "Riley Chen", email: "riley@triffid.ai", role: "employee", status: "active", avatar: "RC", joinedAt: "2024-05-15" },
];

export const projects: Project[] = [
  { id: "p1", name: "E-Commerce Platform", description: "Full-stack e-commerce with payments, inventory, and admin panel", status: "live", assignees: ["3", "4"], createdAt: "2024-06-01", apiKey: "trfk_live_a1b2c3d4e5f6" },
  { id: "p2", name: "Analytics Dashboard", description: "Real-time analytics with charts, filters, and export functionality", status: "deploying", assignees: ["3", "7"], createdAt: "2024-07-15", apiKey: "trfk_dev_x7y8z9w0v1u2" },
  { id: "p3", name: "Chat Application", description: "Real-time messaging with WebSocket, file sharing, and notifications", status: "pending", assignees: ["4", "8"], createdAt: "2024-08-01" },
  { id: "p4", name: "CRM System", description: "Customer relationship management with pipelines and automation", status: "live", assignees: ["3"], createdAt: "2024-08-20", apiKey: "trfk_live_m3n4o5p6q7r8" },
];

export const metrics = {
  cpu: [
    { time: "00:00", value: 35 }, { time: "04:00", value: 28 }, { time: "08:00", value: 62 },
    { time: "12:00", value: 78 }, { time: "16:00", value: 55 }, { time: "20:00", value: 42 },
  ],
  apiCalls: [
    { day: "Mon", calls: 1200 }, { day: "Tue", calls: 1800 }, { day: "Wed", calls: 2200 },
    { day: "Thu", calls: 1900 }, { day: "Fri", calls: 2500 }, { day: "Sat", calls: 800 }, { day: "Sun", calls: 600 },
  ],
  uptime: 99.97,
  totalApiCalls: 11000,
  activeDeployments: 3,
  cloudUsage: { compute: 64, storage: 38, bandwidth: 52 },
};

export const sampleTables = [
  {
    name: "users",
    columns: ["id", "name", "email", "created_at"],
    rows: [
      ["1", "John Doe", "john@example.com", "2024-01-15"],
      ["2", "Jane Smith", "jane@example.com", "2024-02-20"],
      ["3", "Bob Wilson", "bob@example.com", "2024-03-10"],
    ],
  },
  {
    name: "orders",
    columns: ["id", "user_id", "total", "status"],
    rows: [
      ["101", "1", "$299.00", "completed"],
      ["102", "2", "$149.50", "pending"],
      ["103", "1", "$89.99", "shipped"],
    ],
  },
];

export const dummyGeneratedCode = `// Generated by Triffid AI
import express from 'express';
import { PrismaClient } from '@prisma/client';

const app = express();
const prisma = new PrismaClient();

app.use(express.json());

// GET all users
app.get('/api/users', async (req, res) => {
  const users = await prisma.user.findMany();
  res.json(users);
});

// POST create user
app.post('/api/users', async (req, res) => {
  const user = await prisma.user.create({
    data: req.body,
  });
  res.status(201).json(user);
});

app.listen(3000, () => {
  console.log('Server running on port 3000');
});`;
